# Generated by Django 5.0 on 2023-12-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='display_category_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='has_children',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='original_category_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category_id',
            field=models.IntegerField(default=0),
        ),
    ]
