# Generated by Django 5.0 on 2023-12-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_view_alter_product_drop_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='view',
            field=models.IntegerField(default=412),
        ),
    ]
