# Generated by Django 5.0 on 2023-12-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='view',
            field=models.IntegerField(default=672),
        ),
    ]
