# Generated by Django 5.0 on 2023-12-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_content_alter_product_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='view',
            field=models.IntegerField(default=775),
        ),
    ]
